version: '3'

services:
  config-server:
    container_name: config-server
    image: dddpaul/spring-cloud-config-server:2.1.1.RELEASE
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      - BANNER_LOCATION=file:/config/banner.txt
