version: '3'

services:
  config-server:
    container_name: config-server
    image: dddpaul/spring-cloud-config-server:2.1.1.RELEASE
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/dddpaul/spring-cloud-config-repo
      - ENCRYPT_KEY=JqrgXR9BsS33dbpYhMzZHr6T
